/* tslint:disable */
/* eslint-disable */
/**
 * Aktuelle 5 Minuten
 * Aktuelle 5 Minuten API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Controls if certain buttons should be shown to the user in the UI
 * @export
 * @interface AiStatus
 */
export interface AiStatus {
    /**
     * If a ChatGPT link button should be shown
     * @type {boolean}
     * @memberof AiStatus
     */
    chatgpt: boolean;
    /**
     * If a Claude-AI link button should be shown
     * @type {boolean}
     * @memberof AiStatus
     */
    claude: boolean;
}

/**
 * Check if a given object implements the AiStatus interface.
 */
export function instanceOfAiStatus(value: object): boolean {
    if (!('chatgpt' in value)) return false;
    if (!('claude' in value)) return false;
    return true;
}

export function AiStatusFromJSON(json: any): AiStatus {
    return AiStatusFromJSONTyped(json, false);
}

export function AiStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'chatgpt': json['chatgpt'],
        'claude': json['claude'],
    };
}

export function AiStatusToJSON(value?: AiStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chatgpt': value['chatgpt'],
        'claude': value['claude'],
    };
}

