/* tslint:disable */
/* eslint-disable */
/**
 * Aktuelle 5 Minuten
 * Aktuelle 5 Minuten API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleFiguresInnerImage } from './ArticleFiguresInnerImage';
import {
    ArticleFiguresInnerImageFromJSON,
    ArticleFiguresInnerImageFromJSONTyped,
    ArticleFiguresInnerImageToJSON,
} from './ArticleFiguresInnerImage';

/**
 * 
 * @export
 * @interface ArticleFiguresInner
 */
export interface ArticleFiguresInner {
    /**
     * 
     * @type {ArticleFiguresInnerImage}
     * @memberof ArticleFiguresInner
     */
    image: ArticleFiguresInnerImage;
    /**
     * 
     * @type {string}
     * @memberof ArticleFiguresInner
     */
    caption: string;
}

/**
 * Check if a given object implements the ArticleFiguresInner interface.
 */
export function instanceOfArticleFiguresInner(value: object): boolean {
    if (!('image' in value)) return false;
    if (!('caption' in value)) return false;
    return true;
}

export function ArticleFiguresInnerFromJSON(json: any): ArticleFiguresInner {
    return ArticleFiguresInnerFromJSONTyped(json, false);
}

export function ArticleFiguresInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleFiguresInner {
    if (json == null) {
        return json;
    }
    return {
        
        'image': ArticleFiguresInnerImageFromJSON(json['image']),
        'caption': json['caption'],
    };
}

export function ArticleFiguresInnerToJSON(value?: ArticleFiguresInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image': ArticleFiguresInnerImageToJSON(value['image']),
        'caption': value['caption'],
    };
}

