/* tslint:disable */
/* eslint-disable */
/**
 * Aktuelle 5 Minuten
 * Aktuelle 5 Minuten API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleFiguresInnerImage
 */
export interface ArticleFiguresInnerImage {
    /**
     * 
     * @type {string}
     * @memberof ArticleFiguresInnerImage
     */
    src: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleFiguresInnerImage
     */
    alt: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleFiguresInnerImage
     */
    srcset: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleFiguresInnerImage
     */
    title: string;
}

/**
 * Check if a given object implements the ArticleFiguresInnerImage interface.
 */
export function instanceOfArticleFiguresInnerImage(value: object): boolean {
    if (!('src' in value)) return false;
    if (!('alt' in value)) return false;
    if (!('srcset' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function ArticleFiguresInnerImageFromJSON(json: any): ArticleFiguresInnerImage {
    return ArticleFiguresInnerImageFromJSONTyped(json, false);
}

export function ArticleFiguresInnerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleFiguresInnerImage {
    if (json == null) {
        return json;
    }
    return {
        
        'src': json['src'],
        'alt': json['alt'],
        'srcset': json['srcset'],
        'title': json['title'],
    };
}

export function ArticleFiguresInnerImageToJSON(value?: ArticleFiguresInnerImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'src': value['src'],
        'alt': value['alt'],
        'srcset': value['srcset'],
        'title': value['title'],
    };
}

