/* tslint:disable */
/* eslint-disable */
/**
 * Aktuelle 5 Minuten
 * Aktuelle 5 Minuten API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiStatus,
  Count,
} from '../models/index';
import {
    AiStatusFromJSON,
    AiStatusToJSON,
    CountFromJSON,
    CountToJSON,
} from '../models/index';

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * Retrieves the status, if specific AI buttons should be enabled
     * Status for enabled AI buttons
     */
    async aiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ai`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiStatusFromJSON(jsonValue));
    }

    /**
     * Retrieves the status, if specific AI buttons should be enabled
     * Status for enabled AI buttons
     */
    async ai(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiStatus> {
        const response = await this.aiRaw(initOverrides);
        return await response.value();
    }

    /**
     * How many articles/categories exist in the database
     * How many articles/categories exist
     */
    async countRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * How many articles/categories exist in the database
     * How many articles/categories exist
     */
    async count(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.countRaw(initOverrides);
        return await response.value();
    }

}
