/* tslint:disable */
/* eslint-disable */
/**
 * Aktuelle 5 Minuten
 * Aktuelle 5 Minuten API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleContent
 */
export interface ArticleContent {
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    html: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleContent
     */
    plaintext: string;
}

/**
 * Check if a given object implements the ArticleContent interface.
 */
export function instanceOfArticleContent(value: object): boolean {
    if (!('html' in value)) return false;
    if (!('plaintext' in value)) return false;
    return true;
}

export function ArticleContentFromJSON(json: any): ArticleContent {
    return ArticleContentFromJSONTyped(json, false);
}

export function ArticleContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleContent {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'],
        'plaintext': json['plaintext'],
    };
}

export function ArticleContentToJSON(value?: ArticleContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'html': value['html'],
        'plaintext': value['plaintext'],
    };
}

