-- Your SQL goes here
ALTER TABLE articles ADD COLUMN content_html TEXT DEFAULT NULL;

ALTER TABLE articles ADD COLUMN figure_src VARCHAR(255) DEFAULT NULL;
ALTER TABLE articles ADD COLUMN figure_alt VARCHAR(255) DEFAULT NULL;
ALTER TABLE articles ADD COLUMN figure_srcset VARCHAR(255) DEFAULT NULL;
ALTER TABLE articles ADD COLUMN figure_title VARCHAR(255) DEFAULT NULL;
ALTER TABLE articles ADD COLUMN figure_caption VARCHAR(255) DEFAULT NULL;
